import 'package:flutter/material.dart';

const List<String> liveScreensString = [
  "ALL",
  "FAVOURITES",
  "CHANNELS HISTORY",
  "24/7 CINEMANIA",
  "LIVE | PPV EVENTS",
  "LIVE | BETTING",
  "LIVE | IPL IN 4K",
  "LIVE | CRICKET / IPL",
  "LIVE | SPORTS EVENTS",
  "LIVE | RUGBY EVENTS",
  "LIVE | FOOTBALL EVENTS",
  "LIVE | EPL HUB",
  "LIVE | STAR HUB (EPL)",
  "LIVE | EFL HUB",
  "LIVE | SPFL / LOI / IRISH",
  "LIVE | NATIONAL LEAGUE",
  "LIVE | MLS",
  "LIVE | WSL",
  "LIVE | TRILLER TV / UFC",
  "LIVE | F1 / MOTOGP",
  "LIVE | SNOOOKER / DART",
  "LIVE | WORLD SPORTS",
  "SPORTS | CLUBBER TV",
  "SPORTS | SUPERLEAGUE+ / FLORUGBY",
  "SPORTS | NOW HK",
  "SPORTS | OPTUS / NZ SKY SPORTS",
  "SPORTS | PEACOCK",
  "SPORTS | SETANTA",
  "SPORTS | VIDIO",
  "SPORTS | HUB SPORTS",
  "SPORTS | CSPORTS / RUSH",
  "SPORTS | DAZN UK/US/CA",
  "SPORTS | ASTRO SPORTS",
  "SPORTS | ESPN+",
  "SPORTS | STAN / MOLA TV",
  "SPORTS | BEIN MEDIA",
  "SPORTS | BEIN MAX",
  "UK | SPORTS",
  "UK | TNT SPORTS",
  "UK | ENTERAINMENT",
  "UK | REGIONAL & RED BUTTON",
  "UK | MOVIES",
  "UK | KIDS",
  "UK | DOCUMENTRIES",
  "UK | NEWS",
  "UK | MUSIC",
  "UK | RELIGIOUS",
  "IE | IRISH TV",
  "IN/PK | SPORTS",
  "PK | ENTERAINMENT",
  "PK | NEWS",
  "IN | ENTERAINMENT",
  "IN | MOVIES",
  "IN | MUSIC",
  "IN | NEWS",
  "IN | DOCUMENTRIES",
  "IN | RELIGIOUS",
  "INR | PUNJABI",
  "INR | BANGLA",
  "INR | MALAYALAM",
  "INR | MARATHI",
  "INR | GUJRATI",
  "INR | TELUGU",
  "INR | TAMIL",
  "INR | ASSAMESE",
  "INR | KANNADA",
  "INR | ODIA",
  "US | ENTERAINMENT",
  "US | SPECTRUM",
  "US | SPORTS",
  "US | LOCALS",
  "US | INTERNATIONAL",
  "US | GENERAL",
  "US | NBC",
  "US | ASIAN",
  "US | NEWS",
  "US | MOVIES",
  "US | ABC",
  "US | FOX",
  "US | DOCUMENTRIES",
  "US | KIDS",
  "US | MUSIC",
  "US | CBS",
  "US | MLB",
  "US | NBA",
  "US | NFL",
  "US | ESPN",
  "CA | ENTERTAINMENT",
  "CA | SPORTS",
  "CA | FRENCH",
  "CA | DOCUMENTRIES",
  "CA | NEWS",
  "CA | GENERAL",
  "CA | MOVIES",
  "CA | KIDS",
  "CA | MUSIC",
  "CA | CANADA",
  "AR | SPORTS",
  "INT | NEPAL",
  "INT | SRI LANKA",
  "INT | DSTV ENTERTAINMENT",
  "INT | DSTV SPORTS",
  "INT | DSTV MOVIES",
  "INT | DSTV NEWS",
  "INT | DSTV KIDS",
];
List<String> cinematicString = [
  "ALL",
  "FAVOURITE",
  "CONTINUE WATCHING",
  "RECENTLY ADDED",
  "BOX OFFICE HITS",
  "SPORTS REPLAYS",
  "4K MOVIES",
  "4K BOLLYWOOD CLASSIC MOVIE",
  "MULTI AUDIO MOVIES",
  "ENGLISH MOVIES 2023 / 2024",
  "ENGLISH MOVIES 2022",
  "ENGLISH MOVIES 2021",
  "ENGLISH MOVIES 2019-2020",
  "ENGLISH MOVIES 2017-2018",
  "ENGLISH MOVIES 2000-2016",
  "ENGLISH MOVIES 2013",
  "ENGLISH MOVIES 90'S",
  "HINDI MOVIES 2024",
  "HINDI MOVIES 2023",
  "HINDI MOVIES 2022",
  "HINDI MOVIES 2019-2021",
  "HINDI MOVIES 2017-2018",
  "HINDI MOVIES 2000-2016",
  "HINDI MOVIES 90'S",
  "BOLLYWOOD CLASSIC MOVIES",
  "BEST OF 80S MOVIES",
  "SOUTH AFRICAN MOVIES",
  "PAKISTANI MOVIES",
  "PAKISTANI TELEFILMS",
  "KIDS MOVIES",
  "PUNJABI MOVIES",
  "MARATHI MOVIES",
  "GUJRATI MOVIES",
  "MALAYALAM MOVIES",
  "KANNADA MOVIES",
  "TAMIL MOVIES",
  "TELUGU MOVIES 2022-2024",
  "TELUGU MOVIES 2021",
  "TELUGU MOVIES",
  "BANGLA MOVIES",
  "3D DOCUMENTARY AND IMAX COLLECTION",
  "OPRAH WITH MEGHAN & HARRY",
  "TOM & JERRY SERIES",
  "HORROR MOVIES",
  "SUSHANT SINGH RAJPUT COLLECTION",
  "THE LEGEND IRFAN KHAN COLLECTION",
  "THE LEGEND RISHI KAPOOR COLLECTION",
  "007 JAMES BOND COLLECTION",
  "BRUCE LEE MOVIES COLLECTION",
  "CHRISTMAS MOVIE COLLECTION",
  "DENZEL WASHINGTON COLLECTION",
  "ELVIS PRESLEY COLLECTION",
  "GODFATHER COLLECTION",
  "JACKIE CHAN MOVIE COLLECTION",
  "JET LI MOVIES COLLECTION",
  "INDIANA JONES THE COMPLETE ADVENTURE",
  "DISNEY PLUS ANIMATION STUDIOS COLLECTION",
  "THE HARRY POTTER COLLECTIONS",
  "MARVEL MOVIES COLLECTION",
  "GHOST MOVIES COLLECTION",
  "HELL RAISER COLLECTION",
  "CLINT EASTWOOD MOVIES COLLECTION",
  "MARTIN SCORSESE & DANIEL DAY-LEWIS COLLECTION",
  "STAR WARS COLLECTION",
  "FAST AND THE FURIOUS COLLECTION",
  "THE MATRIX COLLECTION",
  "THE MARINE COLLECTION",
  "TWILIGHT SAGA COLLECTION",
  "THE PURGE COLLECTION",
  "THE ROCKY COLLECTION",
  "TRANSPORTER COLLECTION",
  "WRONG TURN COLLECTION",
  "X-MEN COLLECTION",
  "JOY RIDE COLLECTION",
  "JUSTICE LEAGUE COLLECTION",
  "MAX PAYNE COLLECTION",
  "AMERICAN PIE COLLECTION",
  "SPIDER MAN COLLECTION",
  "IP MAN COLLECTION",
  "DEATH RACE COLLECTION",
  "TERMINATOR COLLECTION",
  "TRANSFORMERS COLLECTION",
  "TREMORS COLLECTION",
  "THE HUNGER GAMES COLLECTION",
  "MISSION IMPOSSIBLE COLLECTION",
  "BEVERLY HILLS COP COLLECTION",
  "WESTERN MOVIES",
  "RAMBO COLLECTION",
  "SUPERMAN COLLECTION",
  "STARSHIP TROOPERS COLLECTION",
  "STEP UP MOVIE COLLECTION",
  "MULTILINGUISTIC COLLECTION",
  "GIPPY GAREWAL PUNJABI COLLECTION",
  "DESI MUJRA",
  "PUNJABI STAGE DRAMAS",
  "STAGE DRAMA",
  "GUJARATI NATAK",
  "QURAN MAJEED",
  "MAZE RUNNER",
];

const List<String> cinematicChannelImages = [
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBLaaTuT-wOi-mkpbnT3wvXgWu0EK1ZKP3Bw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIQTXdQjyTo3qbXGO2XPPk6FnFnj54tW3a2A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2oTmz0TrM-RB8BkMHn-jU-EJph0JBgB10EQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK4oTFgazwovoe0YF6VItqQd3Up-KX9hL6cQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtBqeG3NfAkqNYaqX8WNZP-qT9S-U45q0GOQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlFv56f5tXfs_u1Aw5gzJrQsx4MrqYXmMrBA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8cM-_xHkSXl0C4AkQ2jfhQBg8ioD7WyW53Q&s",
];

List<IconData> listIconData = [
  Icons.settings,
  Icons.access_time,
  Icons.queue_play_next_outlined,
  Icons.auto_mode_sharp,
  Icons.access_time_sharp,
  Icons.safety_check_rounded,
  Icons.play_circle_outline_rounded,
  Icons.settings_outlined,
  Icons.play_lesson_rounded,
  Icons.dashboard_outlined,
  Icons.speed,
  Icons.safety_check_rounded,
  Icons.move_down,
  Icons.backup_sharp
];
List<String> listOfNames = [
  "Gerneral Settings",
  "EPG",
  "Stream Format",
  "Automation",
  "Time Format",
  "Parental Control",
  "Player Selection",
  "Player Settings",
  "External Players",
  "Multi Screen",
  "Speed Test",
  "VPN",
  "Switch Device Mode",
  "back & Restore"
];

List<String> listOfCheckBoxsGeneralSetting = [
  "AutoStart on Bootup",
  "Show Full EPG",
  "Active Subtitle",
  "AutoPlay Next Episode in",
  "Auto Clear Cache",
  "Show EPG in Channels List",
  "AutoPlay Channel in Live",
  "Recently Added Limit",
  "Channels History Limit"
];
